version: 0.2
artifacts:
  files:
    - '**/*'
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --production=falsephases:
  build:
    commands:
      - npm run build